services:
  db:
    image: mysql:8.0
    container_name: agencia_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: agencia
      MYSQL_USER: agencia
      MYSQL_PASSWORD: agencia123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  app:
    build: .
    container_name: agencia_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/agencia?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: agencia
      SPRING_DATASOURCE_PASSWORD: agencia123
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    restart: unless-stopped

volumes:
  mysql_data:
