version: '3.8'

services:
  app:
    build: .
    container_name: agencia_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: mvn spring-boot:run
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: agencia_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agencia
      MYSQL_USER: agencia
      MYSQL_PASSWORD: agencia
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
